# Generated by Django 2.1.7 on 2019-03-10 21:09

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [('pm', '0001_initial')]

    operations = [
        TrigramExtension(),
        migrations.RunSQL('set pg_trgm.word_similarity_threshold=0.3'),
        migrations.RunSQL('CREATE INDEX pm_component_code_tgrm ON pm_component USING GIST (code gist_trgm_ops)'),
        migrations.RunSQL('CREATE INDEX pm_component_name_tgrm ON pm_component USING GIST (name gist_trgm_ops)'),
    ]
