# Generated by Django 2.1.7 on 2019-03-31 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0004_project_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deleted_at',
            field=models.DateTimeField(db_index=True, default=None, editable=False, null=True),
        ),
    ]
