# Generated by Django 3.0.2 on 2020-06-03 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0004_auto_20200217_2001'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='group',
            unique_together=set(),
        ),
    ]
