# Generated by Django 2.1 on 2019-04-17 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0005_product_deleted_at'),
    ]

    operations = [
        migrations.RunSQL(
            'CREATE INDEX pm_component_description_tgrm ON pm_component USING GIST (description gist_trgm_ops)'
        ),
    ]
