# Generated by Django 2.1 on 2019-04-18 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0007_auto_20190418_0917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ('-created_at',)},
        ),
    ]
